# Numpy

Paquete para computo numérico
Sirve para:
* Utilizar vectores y matrices
* Cálculos estadísticos y matemáticos

## Bastante rápido y eficiente

In [1]:
# importar numpy
import numpy as np

In [19]:
# crear listas con números primos
numeros_primos = [2,3,5,7,11,13,17,19,23,29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [20]:
# crear un array a partir de una lista
array_primos = np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [21]:
# crear arrays con cero o inicializar un arreglo de numpy
array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# crear arrays con ceros
array_numeros = np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# array con numeros sucesivos
array_pares = np.arange(0,20,2)
# empieza en 0, termina en 20, con paso de 2
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
# haciendo un reshape para 2 dimensiones
array_pares.reshape(2,5)
# arreglo de 2 filas y 5 columnas

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Operaciones Aritméticas

In [25]:
# suponiendo para obtener impares
array_impares = array_pares + 1
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
# multiplicando por 5
array_impares*5

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [27]:
# restando arreglos
array_impares - array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
# division
array_pares / array_impares

array([0.        , 0.66666667, 0.8       , 0.85714286, 0.88888889,
       0.90909091, 0.92307692, 0.93333333, 0.94117647, 0.94736842])

## Metodos asociados a la estadistica

In [29]:
# suma
array_primos.sum()

129

In [30]:
# promedio
array_primos.mean()

12.9

In [31]:
# varianza
array_primos.var()

73.28999999999999

In [33]:
# ordenar un arreglo de numpy
array_fibonacci = np.array([55,0,144,1,21,89,5,8,13,1,34,3,2])
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [34]:
# orden ascendente: de menor a mayor
np.sort(array_fibonacci)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [35]:
# orden descendente: de mayor a menor 
-np.sort(-array_fibonacci)

array([144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,   0])

## Seleccionar elementos

In [36]:
# seleccionar un elemento
A = np.arange(0,20,2).reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [37]:
# seleccionar el primer elemento
A[0,0]

0

In [38]:
# seleccionar algun otro elemento
A[1,3]

16

seleccionar varios elementos


In [39]:
# seleccionar por filas
A[1,:]

array([10, 12, 14, 16, 18])

In [40]:
# seleccionar por columnas
A[:,3]

array([ 6, 16])

In [41]:
# Utilizar filter
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [43]:
# condicion -> para valores menores a 20
array_fibonacci < 20

array([False,  True, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True])

In [44]:
# filtrar para valores menores a 20
array_fibonacci[array_fibonacci<20]

array([ 0,  1,  5,  8, 13,  1,  3,  2])