# Paquetes

In [1]:
# Importando un paquete

In [2]:
import numpy

In [3]:
numpy.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
# Importar un paquete con acronimo (reducción del nombre) 

In [5]:
import numpy as np

In [7]:
# objeto array de numpy

In [8]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
# Cargar una funcion especifica de un paquete

In [10]:
from numpy import arange

In [11]:
arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Función = conjunto de instrucciones que regresan algo
## Método = conjunto de instrucciones que trabajan sobre objetos

In [13]:
# Diferencias entre funciones y metodos

In [14]:
A=np.arange(9)

In [16]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
# Saber el tipo de objeto con -> type
type(A)

numpy.ndarray

In [31]:
# Calculando el promedio con una funcion de numpy -> mean
np.mean(A)

4.0

In [30]:
# Calculando promedio con metodo de objeto
A.mean()

4.0

In [24]:
# Reshape con funciones y metodos

In [28]:
# Transformando un arreglo con funcion de numpy
np.reshape(A,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
# Transformando arreglo con metodo de objeto
A.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])